# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: nodeSetup
        uses: actions/setup-node@v2
        with:
         node-version: '14'
      - name: nodeInstall
        run: npm install
      - name: testRun
        run: npm test
