# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: start running
      - name: use Node@14
        uses: actions/checkout@v2
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        run: npm install
        run: npm test
